version: '3.8'

services:
  vibefm:
    build: .
    ports:
      - "1504:1504"
    environment:
      - NODE_ENV=production
      - PORT=1504
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:1504/api/charts', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    name: vibefm-network
